services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./uploads:/app/uploads
      - ./logs:/app/logs
    environment:
      - FLASK_APP=main.py
      - FLASK_ENV=development
      - HOST=0.0.0.0
      - PORT=8000
      - DEBUG=True
      - MAX_CONTENT_LENGTH=16777216
      - UPLOAD_FOLDER=/app/uploads
      - LOG_FILE=/app/logs/data_processor.log
      - DATABASE_URL=postgresql://bpa-teste:1336@db:5432/bpa-testes-local
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=bpa-teste
      - POSTGRES_PASSWORD=1336
      - POSTGRES_DB=bpa-testes-local
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    restart: unless-stopped

volumes:
  postgres_data: 